{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mbridge.msdk.oversea",
    "module": "interstitialvideo",
    "version": "16.4.61",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "ybz57sd5wvauzb7lms26zkxb3i"
    }
  },
  "variants": [
    {
      "name": "overseaReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "same",
          "version": {
            "requires": "16.4.61"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "videojs",
          "version": {
            "requires": "16.4.61"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "mbjscommon",
          "version": {
            "requires": "16.4.61"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "playercommon",
          "version": {
            "requires": "16.4.61"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "videocommon",
          "version": {
            "requires": "16.4.61"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "reward",
          "version": {
            "requires": "16.4.61"
          }
        }
      ],
      "files": [
        {
          "name": "interstitialvideo-16.4.61.aar",
          "url": "interstitialvideo-16.4.61.aar",
          "size": 9822,
          "sha512": "b7e921be4498ea4facf7c57b1705e651526c9c183fc23cd6cf639b7f95571e0b9ca0f9f34ea574a318b4ab269aacbc00c0319aa2495c827abb3e72219c7e1c74",
          "sha256": "5a9af4abe64c27b65f4ddeab853e892c6dd7c83c54fdc8e6975415b6e5ad7583",
          "sha1": "ed2108bcfff23a4f194e29af4ea75be5197d9a91",
          "md5": "c12df0cb4f34cfbe04dac61fe54d4948"
        }
      ]
    },
    {
      "name": "overseaReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "same",
          "version": {
            "requires": "16.4.61"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "videojs",
          "version": {
            "requires": "16.4.61"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "mbjscommon",
          "version": {
            "requires": "16.4.61"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "playercommon",
          "version": {
            "requires": "16.4.61"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "videocommon",
          "version": {
            "requires": "16.4.61"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "reward",
          "version": {
            "requires": "16.4.61"
          }
        }
      ],
      "files": [
        {
          "name": "interstitialvideo-16.4.61.aar",
          "url": "interstitialvideo-16.4.61.aar",
          "size": 9822,
          "sha512": "b7e921be4498ea4facf7c57b1705e651526c9c183fc23cd6cf639b7f95571e0b9ca0f9f34ea574a318b4ab269aacbc00c0319aa2495c827abb3e72219c7e1c74",
          "sha256": "5a9af4abe64c27b65f4ddeab853e892c6dd7c83c54fdc8e6975415b6e5ad7583",
          "sha1": "ed2108bcfff23a4f194e29af4ea75be5197d9a91",
          "md5": "c12df0cb4f34cfbe04dac61fe54d4948"
        }
      ]
    }
  ]
}
