{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mbridge.msdk.oversea",
    "module": "reward",
    "version": "16.4.41",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "ex5aso3aqbahhpbzommh433qyq"
    }
  },
  "variants": [
    {
      "name": "overseaReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "same",
          "version": {
            "requires": "16.4.41"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "videojs",
          "version": {
            "requires": "16.4.41"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "mbjscommon",
          "version": {
            "requires": "16.4.41"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "playercommon",
          "version": {
            "requires": "16.4.41"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "videocommon",
          "version": {
            "requires": "16.4.41"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "dycreator",
          "version": {
            "requires": "16.4.41"
          }
        }
      ],
      "files": [
        {
          "name": "reward-16.4.41.aar",
          "url": "reward-16.4.41.aar",
          "size": 155914,
          "sha512": "f1c24fa01e63692a108679b6aa70869179100c084e211dbf68d24235d48acd4621db2db877c6c9fa38fec7cfe201deecad5da3380a57ef233a7dff55b2b88bf4",
          "sha256": "110f369d85b077b7016bcf76579a4b36309e8ec47c3dcbe457aa27fbcfad102a",
          "sha1": "53c2fa46a0bea98c59f946c4a4f04e2bbc060bf3",
          "md5": "12c27469b77449a16575b0e44e1f83a5"
        }
      ]
    },
    {
      "name": "overseaReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "same",
          "version": {
            "requires": "16.4.41"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "videojs",
          "version": {
            "requires": "16.4.41"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "mbjscommon",
          "version": {
            "requires": "16.4.41"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "playercommon",
          "version": {
            "requires": "16.4.41"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "videocommon",
          "version": {
            "requires": "16.4.41"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "dycreator",
          "version": {
            "requires": "16.4.41"
          }
        }
      ],
      "files": [
        {
          "name": "reward-16.4.41.aar",
          "url": "reward-16.4.41.aar",
          "size": 155914,
          "sha512": "f1c24fa01e63692a108679b6aa70869179100c084e211dbf68d24235d48acd4621db2db877c6c9fa38fec7cfe201deecad5da3380a57ef233a7dff55b2b88bf4",
          "sha256": "110f369d85b077b7016bcf76579a4b36309e8ec47c3dcbe457aa27fbcfad102a",
          "sha1": "53c2fa46a0bea98c59f946c4a4f04e2bbc060bf3",
          "md5": "12c27469b77449a16575b0e44e1f83a5"
        }
      ]
    }
  ]
}
