{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.okhttp3",
    "module": "okhttp",
    "version": "4.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "okhttp-4.11.0.jar",
          "url": "okhttp-4.11.0.jar",
          "size": 786969,
          "sha512": "9c0a254ab18e6eb2af3f6851771dee5b2e2d6d006f491dd73177cfbbb25005a1d523cf4f6f4cc8622ae0229cc072c43680a7bf1340a5ec6bfadc51e85540afcb",
          "sha256": "ee8f6bd6cd1257013d748330f4ca147638a9fbcb52fb388d5ac93cf53408745d",
          "sha1": "436932d695b2c43f2c86b8111c596179cd133d56",
          "md5": "8f53e26319679de3ea22261b1899a99c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "okhttp-4.11.0.jar",
          "url": "okhttp-4.11.0.jar",
          "size": 786969,
          "sha512": "9c0a254ab18e6eb2af3f6851771dee5b2e2d6d006f491dd73177cfbbb25005a1d523cf4f6f4cc8622ae0229cc072c43680a7bf1340a5ec6bfadc51e85540afcb",
          "sha256": "ee8f6bd6cd1257013d748330f4ca147638a9fbcb52fb388d5ac93cf53408745d",
          "sha1": "436932d695b2c43f2c86b8111c596179cd133d56",
          "md5": "8f53e26319679de3ea22261b1899a99c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "okhttp-4.11.0-javadoc.jar",
          "url": "okhttp-4.11.0-javadoc.jar",
          "size": 261,
          "sha512": "e315924c1105c9052b659c3da1aab2e48ea8bd7557be813f886f9952bfbc9dd59446dd2bd93449e34095f24754c3ac01914066d14e021fd2638bd99c41596351",
          "sha256": "7241a0eccfd3b5a3883316aac2aa13ebe69187b8055ee5b1f159957824be7c45",
          "sha1": "c5d91892aa84d5a6a9a3367b640607d9524974cd",
          "md5": "9d11e09fde78c85142d3cfb195ebbe7c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "okhttp-4.11.0-sources.jar",
          "url": "okhttp-4.11.0-sources.jar",
          "size": 368252,
          "sha512": "396e22a01a10845f1a5cc98f695bfc2e9130f40d92b2c58c1f198cc4bd1717dfa63fa78832d1c163f0adbf3af4716ff1888a3c93e4794b864b03b5518f6719f0",
          "sha256": "98c2211248eabc4fe4cef43d9ef6f246d692ba83d47dd6b641c3a5ac26c0450a",
          "sha1": "9bfc7526f84edf546cf34aaf23bdbc2b30147c34",
          "md5": "542b75f8eab11eb53eb5c0bd3d5696e6"
        }
      ]
    }
  ]
}
