{
  "formatVersion": "1.1",
  "component": {
    "url": "../../okio/3.2.0/okio-3.2.0.module",
    "group": "com.squareup.okio",
    "module": "okio",
    "version": "3.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "okio-jvm-3.2.0.jar",
          "url": "okio-jvm-3.2.0.jar",
          "size": 345115,
          "sha512": "7a847597b02d34cb754474218d83bbf4241c0d76da025b53b79ff4513fe80ab2901341802d1a8c4bd8bd0a243237ff2a1e50a1fedcc8bc7be1c9e5a36788fc6f",
          "sha256": "b642baef4c570055de4cb3d1667b2b16dced901ff8066345a063691aa06025a4",
          "sha1": "332d1c5dc82b0241cb1d35bb0901d28470cc89ca",
          "md5": "93417dbcbbb0e56d272b7ad5b28afede"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "okio-jvm-3.2.0.jar",
          "url": "okio-jvm-3.2.0.jar",
          "size": 345115,
          "sha512": "7a847597b02d34cb754474218d83bbf4241c0d76da025b53b79ff4513fe80ab2901341802d1a8c4bd8bd0a243237ff2a1e50a1fedcc8bc7be1c9e5a36788fc6f",
          "sha256": "b642baef4c570055de4cb3d1667b2b16dced901ff8066345a063691aa06025a4",
          "sha1": "332d1c5dc82b0241cb1d35bb0901d28470cc89ca",
          "md5": "93417dbcbbb0e56d272b7ad5b28afede"
        }
      ]
    }
  ]
}
